---
# Source: abbot/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: abbot
  labels:
    helm.sh/chart: abbot-0.1.0
    app.kubernetes.io/name: abbot
    app.kubernetes.io/instance: abbot
    arhat.dev/role: Abbot
    app.kubernetes.io/version: "latest"
    app.kubernetes.io/managed-by: Helm
type: Opaque
data:
  config.yaml: YWJib3Q6CiAgbGlzdGVuOiB1bml4Oi8vL3Zhci9ydW4vYWJib3Quc29jawogIGxvZzoKICAtIGZpbGU6IHN0ZGVycgogICAgZm9ybWF0OiBjb25zb2xlCiAgICBsZXZlbDogdmVyYm9zZQpjb250YWluZXJOZXR3b3JrOgogIGNuaVBsdWdpbnNMb29rdXBQYXRoczoKICAtIC9vcHQvY25pL2JpbgogIGNvbnRhaW5lckludGVyZmFjZU5hbWU6IGV0aDAKICBkYXRhRGlyOiAvdmFyL2xpYi9hYmJvdC9jb250YWluZXIKICB0ZW1wbGF0ZTogfAogICAgewogICAgICAiY25pVmVyc2lvbiI6ICIwLjMuMSIsCiAgICAgICJuYW1lIjogImFiYm90IiwKICAgICAgInBsdWdpbnMiOiBbCiAgICAgICAgewogICAgICAgICAgInR5cGUiOiAiYnJpZGdlIiwKICAgICAgICAgICJicmlkZ2UiOiAiYWJib3QwIiwKICAgICAgICAgICJpc0dhdGV3YXkiOiB0cnVlLAogICAgICAgICAgImlzRGVmYXVsdEdhdGV3YXkiOiB0cnVlLAogICAgICAgICAgImlwTWFzcSI6IHRydWUsCiAgICAgICAgICAiZm9yY2VBZGRyZXNzIjogdHJ1ZSwKICAgICAgICAgICJpcGFtIjogewogICAgICAgICAgICAidHlwZSI6ICJob3N0LWxvY2FsIiwKICAgICAgICAgICAgInJhbmdlcyI6IFt7eyBpZiBndCAobGVuIC5JUHY0U3VibmV0KSAwIH19CiAgICAgICAgICAgICAgW3sKICAgICAgICAgICAgICAgICJzdWJuZXQiOiAie3sgLklQdjRTdWJuZXQgfX0iLAogICAgICAgICAgICAgICAgInJvdXRlcyI6IFt7ICJkc3QiOiAiMC4wLjAuMC8wIiB9XQogICAgICAgICAgICAgIH1de3sgZW5kIH19e3sgaWYgYW5kIChndCAobGVuIC5JUHY2U3VibmV0KSAwKSAoZ3QgKGxlbiAuSVB2NFN1Ym5ldCkgMCkgfX0se3sgZW5kIH19e3sgaWYgZ3QgKGxlbiAuSVB2NlN1Ym5ldCkgMCB9fQogICAgICAgICAgICAgIFt7CiAgICAgICAgICAgICAgICAic3VibmV0IjogInt7IC5JUHY2U3VibmV0IH19IgogICAgICAgICAgICAgIH1de3sgZW5kIH19CiAgICAgICAgICAgIF0KICAgICAgICAgIH0KICAgICAgICB9LAogICAgICAgIHsKICAgICAgICAgICJ0eXBlIjogInBvcnRtYXAiLAogICAgICAgICAgImNhcGFiaWxpdGllcyI6IHsgInBvcnRNYXBwaW5ncyI6IHRydWUgfQogICAgICAgIH0sCiAgICAgICAgewogICAgICAgICAgInR5cGUiOiAiYmFuZHdpZHRoIiwKICAgICAgICAgICJjYXBhYmlsaXRpZXMiOiB7ICJiYW5kd2lkdGgiOiB0cnVlIH0KICAgICAgICB9CiAgICAgIF0KICAgIH0KaG9zdE5ldHdvcms6CiAgaW50ZXJmYWNlczogW10KICBwcm94aWVzOiBbXQ==
---
# Source: abbot/templates/daemonset.yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: abbot
  labels:
    helm.sh/chart: abbot-0.1.0
    app.kubernetes.io/name: abbot
    app.kubernetes.io/instance: abbot
    arhat.dev/role: Abbot
    app.kubernetes.io/version: "latest"
    app.kubernetes.io/managed-by: Helm
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: abbot
      app.kubernetes.io/instance: abbot
      arhat.dev/role: Abbot
  template:
    metadata:
      labels:
        app.kubernetes.io/name: abbot
        app.kubernetes.io/instance: abbot
        arhat.dev/role: Abbot
    spec:
      securityContext:
        {}
      nodeSelector:
        arhat.dev/namespace: default
      tolerations:
        - key: arhat.dev/namespace
          value: default
        - key: node.kubernetes.io/unschedulable
          operator: Exists
      hostPID: true
      hostNetwork: true
      containers:
        - name: abbot # abbot container name MUST be abbot
          image: "docker.io/arhatdev/abbot:latest"
          imagePullPolicy: Always
          command:
            - /abbot
            - -c
            - /etc/abbot/config.yaml
          securityContext:
            privileged: true
          # TODO: implement liveness probe
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          volumeMounts:
          - name: config
            mountPath: /etc/abbot
          - name: xtables-lock
            mountPath: /run/xtables.lock
          resources:
            {}
      volumes:
      - name: xtables-lock
        hostPath:
          path: /run/xtables.lock
          type: FileOrCreate
      - name: config
        secret:
          secretName: abbot
