apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "abbot.fullname" . }}
  labels:
    {{- include "abbot.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{- .Values.config | toYaml | nindent 4 }}
